function(oxford_comma _var)
  if(ARGC EQUAL 2)
    set(${_var} "${ARGV1}" PARENT_SCOPE)
  elseif(ARGC EQUAL 3)
    set(${_var} "${ARGV1} and ${ARGV2}" PARENT_SCOPE)
  else()
    set(_count 3)
    set(_glue)
    set(_result)
    foreach(_arg ${ARGN})
      set(_result "${_result}${_glue}${_arg}")
      if(_count LESS ARGC)
        set(_glue ", ")
      else()
        set(_glue ", and ")
      endif()
      math(EXPR _count "${_count}+1")
    endforeach()
    set(${_var} "${_result}" PARENT_SCOPE)
  endif()
endfunction()
